### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Shidapu** [Andre601/IAxPresenceFootsteps#1]
I haave ItemsAdder installed and working, but this plugin posts this in console:

[21:13:43 INFO]: [IAxPresenceFootsteps] Enabling IAxPresenceFootsteps v1.1.0
[21:13:43 INFO]: [IAxPresenceFootsteps] Found PaperMC. Using native message system from it...
[21:13:43 INFO]: [IAxPresenceFootsteps] ItemsAdder was not found! IAxPresenceFootsteps requires this plugin to work.
[21:13:43 INFO]: [IAxPresenceFootsteps] Disabling IAxPresenceFootsteps v1.1.0

**Comment by Andre601** [comment]
I'm 120% sure that this is not an issue on my end.
I have ItemsAdder properly defined as a soft-depend, so that Spigot will load it AFTER ItemsAdder itself.

Relevant lines:
https://github.com/Andre601/IAxPresenceFootsteps/blob/45db1168e745337f57412ebd8b6f50c8ddba02eb/src/main/resources/plugin.yml#L8-L9

https://github.com/Andre601/IAxPresenceFootsteps/blob/45db1168e745337f57412ebd8b6f50c8ddba02eb/src/main/java/ch/andre601/iaxpresencefootsteps/IAxPresenceFootsteps.java#L38-L42

Next, another user had the same issue and from what we gathered is another plugin messing up the plugin loading order. In their case was it Slimefun, so if you're using that plugin, remove it and report the issues to them.
There is nothing in this plugin that would make it load before ItemsAdder, as it uses Spigot-API stuff.

**Comment by Shidapu** [comment]
Wierd. Might it be that there is some kind of compatibility issue with Paper? I'm not using spigot.

Also not using that plugin you mentioned.

**Comment by Andre601** [comment]
Can't be a paper issue as I test my plugins on a paper 1.18.2 server.
Maybe share the plugins you actually use. Also, test your setup on a test server and slowly remove one plugin after the other to see what could cause it.

**Comment by Shidapu** [comment]
Plugins (56): AdvancedEnchantments, AlwaysOnline*, AsyncWorldEdit, BetterPortals, Chunky, ChunkyBorder, CMILib, CoreProtect, DeluxeMenus, dynmap, Dynmap-Towny, EpicAnchors, EpicBackpacks, EpicFurnaces, EpicLevels, Essentials, EssentialsDiscord, EssentialsGeoIP, EssentialsProtect, ExcellentShop, floodgate, Geyser-Spigot, GlowAPI, HolographicDisplays, IAxPresenceFootsteps, ItemsAdder, ItemsAdder-WorldEdit, Jobs, LagAssist, LibsDisguises, LightAPI, LocketteX, LoneLibs, LuckPerms, ModelEngine, MOTD, MythicMobs, NexEngine, PacketListenerApi, PlaceholderAPI, ProtocolLib, RPGhuds, ServerBooster, SurvivalMechanics, Towny, TownyChat, TownyFlight, UltimateModeration, UltimateTimber, Vault, Vehicles, ViaBackwards, ViaVersion, WhatIsThis, WorldEdit, WorldGuard

Paper 1.18.2.

**Comment by Andre601** [comment]
Hmmmm...

Comparing your list with the one from the person who reported a similar issue before, the only common plugins - excluding my own and ItemsAdder of course - seem to be Essentials, floodgate, ItemsAdder-WorldEdit, LibsDisguises, LightAPI, LuckPerms, PlaceholderAPI, ProtocolLib, Vault, WorldEdit and WorldGuard.

So try testing with those plugins. If it works does it mean the plugin causing this issue is in the other group. If it doesn't work, remove the plugins one by one and see again until it actually works.

My personal guess goes towards either ProtocolLib or floodgate as they do some stuff that may or may not require direct usage of server code which could affect things (Also ProtocolLib v5 is known to break a lot of compatibility with plugins, so there is also that).

**Comment by Andre601** [comment]
Quick update: After asking in the PaperMC Discord does it seem like that there is an actual issue with the plugin load order when a huge amount of plugins (100+ mentioned in [this particular issue](https://github.com/PaperMC/Paper/issues/5992)) is loaded.
This issue seems to exist in both SpigotMC and PaperMC and is nothing I myself can fix that reliable...

**Comment by Andre601** [comment]
I tried to implement a fix and hope it works:
https://github.com/Andre601/IAxPresenceFootsteps/releases/tag/v1.2.0

**Comment by Shidapu** [comment]
I just wanted to say thanks for implementing a fix and it works wonders!
